apiVersion: v1
parameters:
  GCPzone:
    default: "asia-southeast1-c"
  AWSregion:
    default: "ap-southeast-1"
  AzureRG:
    default: "AzureRG"
triggers:
- name: schedule
  source:
    type: schedule
    schedule: '0 0 28 1 *'
steps:
- name: gcp-step-instance-list
  image: relaysh/gcp-step-instance-list
  spec:
    google:
      service_account_info: ${connections['gcp']['GCPconnection']}
      zone: ${parameters.GCPzone}
- name: approval
  description: Wait for approval
  type: approval
  dependsOn:
  - gcp-step-instance-list
  - aws-ec2-step-instances-describe
  - azure-virtual-machines-step-vm-list
- name: gcp-step-instance-stop
  image: relaysh/gcp-step-instance-stop
  spec:
    google:
      service_account_info: ${connections['gcp']['GCPconnection']}
      zone: ${parameters.GCPzone}
    instances: ${outputs.'gcp-step-instance-list'.'instances'}
  dependsOn: approval
- name: approval1
  description: Wait for approval
  type: approval
  dependsOn:
  - gcp-step-instance-stop
  - aws-stop-instances
- name: gcp-step-instance-start
  image: relaysh/gcp-step-instance-start
  spec:
    google:
      service_account_info: ${connections['gcp']['GCPconnection']}
      zone: ${parameters.GCPzone}
    instances: ${outputs.'gcp-step-instance-list'.'instances'}
  dependsOn: approval1
- name: aws-ec2-step-instances-describe
  image: relaysh/aws-ec2-step-instances-describe
  spec:
    aws:
     &aws
      connection:
        !Connection { type: aws, name: aws-account }
      region: !Parameter AWSregion
  
- name: aws-filter-instances
  image: relaysh/core:latest-python
  spec:
    instances:
      !Output { from: aws-ec2-step-instances-describe, name: instances }
  inputFile: https://raw.githubusercontent.com/atlgithub2308/filter-aws-instance/main/filter.py
  dependsOn: approval
  
- name: aws-stop-instances
  dependsOn: aws-filter-instances
  image: relaysh/aws-ec2-step-instances-stop
  spec:
    aws: *aws
    instanceIDs:
      !Output { from: aws-filter-instances, name: instanceIDs }
- name: azure-virtual-machines-step-vm-list
  image: relaysh/azure-virtual-machines-step-vm-list
  spec:
    azure:
      connection: ${connections['azure']['Azure']}
    resourceGroup: ${parameters.AzureRG}
