apiVersion: v1
parameters:
  GCPzone:
    default: "asia-southeast1-c"
  AWSregion:
    default: "ap-southeast-1"
  AzureRG:
    default: "AzureRG"
triggers:
- name: schedule
  source:
    type: schedule
    schedule: '0 0 28 1 *'
steps:
- name: gcp-step-instance-list
  image: relaysh/gcp-step-instance-list
  spec:
    google:
      service_account_info: ${connections['gcp']['GCPconnection']}
      zone: ${parameters.GCPzone}

- name: approval
  description: Wait for approval
  type: approval
  dependsOn:
  - gcp-step-instance-list
  - aws-ec2-step-instances-describe
  - azure-virtual-machines-step-vm-list

- name: gcp-step-instance-stop
  image: relaysh/gcp-step-instance-stop
  spec:
    google:
      service_account_info: ${connections['gcp']['GCPconnection']}
      zone: ${parameters.GCPzone}
    instances: ${outputs.'gcp-step-instance-list'.'instances'}
  dependsOn: approval

- name: approval1
  description: Wait for approval
  type: approval
  dependsOn:
  - gcp-step-instance-stop
  - aws-ec2-step-instances-stop

- name: gcp-step-instance-start
  image: relaysh/gcp-step-instance-start
  spec:
    google:
      service_account_info: ${connections['gcp']['GCPconnection']}
      zone: ${parameters.GCPzone}
    instances: ${outputs.'gcp-step-instance-list'.'instances'}
  dependsOn: approval1

- name: aws-ec2-step-instances-describe
  image: relaysh/aws-ec2-step-instances-describe
  spec:
    aws:
      connection: ${connections['aws']['aws-account']}
      region: ${parameters.AWSregion}

- name: aws-ec2-step-instances-stop
  image: relaysh/aws-ec2-step-instances-stop
  spec:
    aws:
      connection: ${connections['aws']['aws-account']}
      region: ${parameters.AWSregion}
    instanceIDs: [ 'i-09c6ae1ffb52bc579' ]
  dependsOn: approval

- name: azure-virtual-machines-step-vm-list
  image: relaysh/azure-virtual-machines-step-vm-list
  spec:
    azure:
      connection: ${connections['azure']['Azure']}
    resourceGroup: ${parameters.AzureRG}
